server:
  port: 9090
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
spring:
  application:
    # 应用名称 可选
    name: reggie_take_out
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.195.128:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: admin
#      password: '@Lz15195248827'
  main:
    allow-bean-definition-overriding: true # 允许bean覆盖
  shardingsphere:
    props:
      sql:
        show: true
    sharding:
      default-data-source-name: master #配置默认数据源ds1 默认数据源,主要用于写.如果和masterslave节点都不配置，则三个数据源都会当作salve，在新增\修改\删除会报错
    masterslave:
      name: ms #配置主从名称
      master-data-source-name: master #置主库master,负责数据的写入
      slave-data-source-names: slave #配置从库slave节点
      load-balance-algorithm-type: round_robin #配置slave节点的负载均衡均衡策略,采用轮询机制
    datasource:
      names: master,slave
      master: # 配置主库
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.195.128:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: '@Lz15195248827'
      slave: # 配置从库
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.195.129:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: '@lz15195248827'
  redis:
    host: 192.168.195.128
    port: 6379
    database: 0
    # https://segmentfault.com/a/1190000023040110 具体的使用方法教程
    # jedis 与 lettuce 连接池的区别
    # 1. jedis 直接连接 Redis 服务，  非线程安全  如果不使用 连接池， 为每个 RedisConnection 实例增加新的物理连接
    # 2. lettuce 可伸缩，             线程安全  完全非阻塞的 Redis 客户端  ， 多个线程可以共享一个 RedisConnection  使用Netty NIO框架管理多个连接， 提供异步与同步数据访问方式，
    #    构建非阻塞的反应性应用程序
    lettuce:
      # redis 连接池配置
      pool:
        max-active: 8 # 最大连接数
        max-idle: 4 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
#        max-wait: -1ms # 连接池最大阻塞等待时间 负值表示没有限制
  cache:
    type: redis
#    redis:
#      time-to-live: 18000

reggie:
  path: D:\picture\


